version: 2
updates:

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "05:20"
  open-pull-requests-limit: 10
  reviewers:
  - algolia/foundation
  - algolia/security
  labels:
  - dependencies
