version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@13.16.7

executors:
  golang:
    docker:
      - image: cimg/go:1.22
  codacy:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  golangci-lint:
    executor: golang
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: &restore-cache
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: |
            go mod download
      - run:
          name: Go fmt
          command: |
            RES="$(gofmt -s -l .)"
            if [ -n "${RES}" ]
            then
              echo "${RES}"
              exit 1
            fi
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      - run:
          name: GolangCI Lint
          command: golangci-lint run
      - save_cache: &save-cache
          paths:
            - /home/circleci/go/pkg/mod
          key: go-mod-{{ checksum "go.sum" }}
  test:
    executor: golang
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          <<: *restore-cache
      - run:
          name: Install dependencies
          command: |
            go mod download
      - run:
          name: Test
          command: |
            make test
            cp -f build/cover.out /tmp/cover.out
      - persist_to_workspace:
          root: /tmp
          paths:
            - "cover.out"
      - run:
          name: Coverage report
          command: |
            make coverage
      - store_artifacts:
          path: build/coverage.html
      - save_cache:
          <<: *save-cache
  codacy-coverage:
    executor: codacy
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Publish coverage report to Codacy
          command: |
            sed -i -e 's@^gopkg.in/algolia/openvpn-auth-okta.v2/@@' /tmp/cover.out
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r /tmp/cover.out

workflows:
  lint_test_build:
    jobs:
      - golangci-lint
      - test:
          requires:
            - golangci-lint
      - codacy-coverage:
          requires:
            - test
